name: Docker CI/CD

on:
  push:
    branches:
      - feature/add-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # should be 'feson56' in your GitHub secrets
          password: ${{ secrets.DOCKER_TOKEN }}      # your Docker personal access token stored as a secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            feson56/sample-node-project:latest
            feson56/sample-node-project:${{ github.sha }}
